### ISSUE TITLE
Could not load lib 'libspng.so' via classloader

### ISSUE THREAD

**Issue by kdekooter** [criteo/JVips#106]
```
ERROR com.criteo.vips.Vips:99 Could not load lib 'libheif.so' via classloader
ERROR com.criteo.vips.Vips:99 Could not load lib 'libspng.so' via classloader
```
How can we fix this? 

Environment: Ubuntu 20.4, JDK 16

**Comment by warrenseine** [comment]
These are marked as ERROR but do not prevent JVips from working. libheif is a specific file format support library and libspng is an alternative PNG processing library. You shouldn't need them in common use cases, so you can safely ignore these errors.

However, if you do need them, you should rebuild the project with specific options to compile and bundle these libraries in the .jar file. Have a look at [CMakeLists.txt](https://github.com/criteo/JVips/blob/38fe1f6d24df7e01bf661ed52faf0db568776816/CMakeLists.txt#L72) for details.

**Comment by kdekooter** [comment]
Thanks for the swift response @warrenseine. Maybe lower the logging level to "WARNING" then?
