### ISSUE TITLE
Garbled results - is there a limit in concurrent invocations?

### ISSUE THREAD

**Issue by kdekooter** [criteo/JVips#108]
We are using libvips in a (spring boot) servlet application. If we render a lot of thumbnails at once thumbnails often get garbled:

![image](https://user-images.githubusercontent.com/508983/142883605-66c188bd-7afc-44af-9856-66dd5b0f7f0f.png)

where we would expect this:

![image](https://user-images.githubusercontent.com/508983/142883672-a5322c9b-46f4-4b13-a56c-db87abb9576d.png)

Is there a limit in the number of threads calling JVips?

**Comment by esiqveland** [comment]
Did you figure this out?

**Comment by kdekooter** [comment]
Been digging in my git repo to see if and how I fixed this - didn't find. 
Cranking up the Java memory to 8G might have helped.

Are you having the sames issues?

**Comment by esiqveland** [comment]
No, I am not seeing it in our test data set, but we serve too many thumbs to inspect if they end up corrupt. I just wondered if you figured it out, as we are running highly concurrent.

**Comment by kdekooter** [comment]
The issue vanished on our end. Closing this.
