### ISSUE TITLE
add vips_thumbnail

### ISSUE THREAD

**Issue by JohannesBeranek** [criteo/JVips#122]
Would be nice if you could add a binding for vips_thumbnail, because vips_thumbnail_image can't take advantage of on-load shrinking, but vips_thumbnail can

**Comment by dbouron** [comment]
Hi,
I will have a look this weekend if I am free time :)

**Comment by dbouron** [comment]
Hi,
I pushed this [PR](https://github.com/criteo/JVips/pull/124). I will close this issue in the next days.

**Comment by JohannesBeranek** [comment]
@dbouron perfect, thank you very much!
