### ISSUE TITLE
Post a downloadable prebuilt binary

### ISSUE THREAD

**Issue by DominicWatson** [criteo/JVips#23]
Thanks for this awesome lib. I've managed to build it locally on my Linux desktop. However, I had all sorts of issues - various functionality such as auto rotation of images fails when you do not have all the libs available. Installing libexif and libtiff for example will change the capabilities available.

Would be great to have a built jar / built jars to download, even if just in the releases in Github so those unfamiliar with C + all the joys of building can get going a bit quicker.

**Comment by dbouron** [comment]
Hello @DominicWatson 
Yes, there is lots of missing bindings. Some image formats haven't been added for the moment (tiff, svg, ...). This is why some libraries are missing.
I will upload a built jar with both Windows 64 and Linux 64 embedded libraries in the next days.

**Comment by dbouron** [comment]
Done, you can download the prebuilt jar file [here](https://github.com/criteo/JVips/releases/tag/1.0.0-alpha).
I close this issue as implementing others bindings is a separated issue.

**Comment by DominicWatson** [comment]
Nice one, thank you @dbouron :)
