### ISSUE TITLE
./build.sh --without-w64 --without-linux --with-macos can not worked?

### ISSUE THREAD

**Issue by jiangdongguo** [criteo/JVips#62]
Hi, There is a problem.When I excute "./build.sh --without-w64 --without-linux --with-macos", there print those infos:

++ pwd
+ BASEDIR=/Users/jj/LearningProjects/JVips/JVips
+ BUILD_LINUX=1
+ BUILD_WIN64=0
+ BUILD_MACOS=0
+ DIST=0
+ DEBUG=0
+ JOBS=8
+ BUILD_TYPE=Release
+ RUN_TEST=1
+ RUN_BENCHMARK=0
+ MAVEN_ARGS=--batch-mode
+ true
+ case "$1" in
+ BUILD_WIN64=0
+ shift
+ true
+ case "$1" in
+ BUILD_LINUX=0
+ shift
+ true
+ case "$1" in
+ BUILD_MACOS=1
+ shift
+ true
+ case "$1" in
+ break
+ '[' 8 -le 0 ']'
+ '[' 0 -eq 1 ']'
+ export JOBS
+ export DEBUG
+ export BUILDDIR=/Users/jj/LearningProjects/JVips/JVips/build
+ BUILDDIR=/Users/jj/LearningProjects/JVips/JVips/build
++ which cmake3
++ which cmake
+ CMAKE_BIN=

Can you tell me what does mean?Tks!

**Comment by warrenseine** [comment]
Hello @jiangdongguo, it looks like you're simply missing CMake. Can you first run `./setup-for-macos.sh` and see how it goes?

**Comment by jiangdongguo** [comment]
Thanks for your reply.It worked!But there is another error---"clang: error: linker command failed with exit code 1 (use -v to see invocation)"，how can I solve it?Thank you again.

**Comment by jiangdongguo** [comment]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityInternal.h:4478:30: note: 
      expanded from macro '__API_A_BEGIN'
    #define __API_A_BEGIN(x) _Pragma(__API_RANGE_STRINGIFY (clang attribute (__attribute__((availability(__API_AVAILABLE_PLATFO...
                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityInternal.h:4485:117: error: 
      _Pragma takes a parenthesized string literal
    #define __API_AVAILABLE_BEGIN6(a,b,c,d,e,f) __API_A_BEGIN(a) __API_A_BEGIN(b) __API_A_BEGIN(c) __API_A_BEGIN(d) __API_A_BEG...
                                                                                                                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityInternal.h:4478:30: note: 
      expanded from macro '__API_A_BEGIN'
    #define __API_A_BEGIN(x) _Pragma(__API_RANGE_STRINGIFY (clang attribute (__attribute__((availability(__API_AVAILABLE_PLATFO...
                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityInternal.h:4485:134: error: 
      _Pragma takes a parenthesized string literal
  ...__API_AVAILABLE_BEGIN6(a,b,c,d,e,f) __API_A_BEGIN(a) __API_A_BEGIN(b) __API_A_BEGIN(c) __API_A_BEGIN(d) __API_A_BEGIN(e) __API_...
                                                                                                                              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityInternal.h:4478:30: note: 
      expanded from macro '__API_A_BEGIN'
    #define __API_A_BEGIN(x) _Pragma(__API_RANGE_STRINGIFY (clang attribute (__attribute__((availability(__API_AVAILABLE_PLATFO...
                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityInternal.h:4525:50: error: 
      _Pragma takes a parenthesized string literal
    #define __API_DEPRECATED_BEGIN_MSG3(msg,a,b) __API_D_BEGIN(msg,a) __API_D_BEGIN(msg,b)
                                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityInternal.h:4522:35: note: 
      expanded from macro '__API_D_BEGIN'
    #define __API_D_BEGIN(msg, x) _Pragma(__API_RANGE_STRINGIFY (clang attribute (__attribute__((availability(__API_DEPRECATED_...
                                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityInternal.h:4525:71: error: 
      _Pragma takes a parenthesized string literal
    #define __API_DEPRECATED_BEGIN_MSG3(msg,a,b) __API_D_BEGIN(msg,a) __API_D_BEGIN(msg,b)
                                                                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityInternal.h:4522:35: note: 
      expanded from macro '__API_D_BEGIN'
    #define __API_D_BEGIN(msg, x) _Pragma(__API_RANGE_STRINGIFY (clang attribute (__attribute__((availability(__API_DEPRECATED_...




ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [tificc] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [lib/lcms2/src/lcms2-stamp/lcms2-build] Error 2
make[1]: *** [lib/CMakeFiles/lcms2.dir/all] Error 2
make: *** [all] Error 2
+ echo 'Linux JVips build failed'
Linux JVips build failed
+ exit 1

**Comment by warrenseine** [comment]
Are you sure you’re still running with `--without-linux`? The last line of your log makes me think you’re trying to build for Linux on macOS.

**Comment by jiangdongguo** [comment]
sorry,I forgot it. I tried again,it was successfull.Thank you so much and for your great project!
