### ISSUE TITLE
How to clone VipsImage

### ISSUE THREAD

**Issue by francm** [criteo/JVips#63]
I am trying to produce many image variant from original image. Every variant has different size and original source image can be quite big.

So, my plan was to load original image to memory, apply safe resize to shrink possibly huge original and for every single required variant clone in-memory image, apply final resize operations and write to target path and format. But i am struggling with cloning.

```java
// first approach is just to create new Vips image from existing instance - but new image is empty
VipsImage result = new VipsImage(original,new PixelPacket(background.getRed(), background.getGreen(), background.getBlue(), alpha));
// so additionaly i tried compose original to new instance
result.compose(original);
```

Solution with compose works, but performance is even worse then simple full open original and resize, which doesn't make sense for me. What i am doing wrong?

I have to use this solution, where re-encoding is required thus, image quality is reduced - but operation is almost ten times faster then clone with compose.

```java
// clone with write to jpg and read again
byte[] bytes = original.writeToArray(VipsImageFormat.JPG, 100, false);
VipsImage result = new VipsImage(bytes, bytes.length);
```

**Comment by dbouron** [comment]
Hello,

> first approach is just to create new Vips image from existing instance - but new image is empty
Yes, `VipsImage(img, pixelPacket)` creates an new images with the same dimension than the image passed in parameter and fill it with the `pixelPacket`

I will implement a clone() method which copy the VipsImage

**Comment by dbouron** [comment]
Here is the PR -> https://github.com/criteo/JVips/pull/65
