### ISSUE TITLE
Loading VipsImage natively via file path

### ISSUE THREAD

**Issue by TimoZikeli** [criteo/JVips#64]
Hi,
I'm wondering if it's possible to load a VipsImage natively by passing a file's path to the libvips library instead of loading the ByteBuffer into the JVM memory. Would that improve performance?

Thanks,
Kind regards,
Timo

**Comment by dbouron** [comment]
Hello,
I am not sure that it will improve the performance, but we could bind the function which loads an image from a path file

**Comment by TimoZikeli** [comment]
That would be great!

**Comment by dbouron** [comment]
Hello,
Here is the pull request: https://github.com/criteo/JVips/pull/66
