### ISSUE TITLE
Bad quality of resized images

### ISSUE THREAD

**Issue by TimoZikeli** [criteo/JVips#72]
Hi,
I just noticed that the quality of resized images is worse than resizing with Photoshop.
I think the reason is that Photoshop uses the BICUBIC algorithm by default. JVips uses the `vips_thumbnail_image` method. It would be really important for me to have a resize method which images with as high quality as possible. Maybe you can specify the bicubic parameter by default or at least add an option for it. 
Thanks!

**Comment by warrenseine** [comment]
Actually, I think we should rename the current method to `thumbnailImage()`, and a separate `resize()` which would actually call `vips_resize()` (and use bicubic interpolation by default).

There is ongoing work to generate the bindings automatically. I think this would solve your issue perfectly, but in the meantime, adding a separate `resize()` method is probably the way to go.

**Comment by dbouron** [comment]
Than you @anthonyroussel for your patch. I close this issue since it has been merged
