### ISSUE TITLE
Writing Image to File Support

### ISSUE THREAD

**Issue by rajasagashe** [criteo/JVips#84]
I'm wondering if directly calling the libvips write_to_file method would improve performance as opposed to what I'm doing below? Is that on the roadmap to add?
```
        byte[] out = img.writeToArray(format, 92, false);
        ByteArrayInputStream input_stream= new ByteArrayInputStream(out);
        BufferedImage final_buffered_image = ImageIO.read(input_stream);
        ImageIO.write(...);
```
If the write directly happened with a native method then the first 3 lines wouldn't be necessary and this would save 10% of the time for my use case. The most expensive out of the first 3 lines is the `writeToArray`.

**Comment by dbouron** [comment]
Hello,
Yes, it is in the roadmap. The binding should be generated by our python script.

**Comment by dbouron** [comment]
Hi,
Finally,  I added this bidding in https://github.com/criteo/JVips/pull/90
I will close this issue once it is merged on the master branch
