### ISSUE TITLE
How to prevent libvips / JVips from creating a humongous amount of temp files?

### ISSUE THREAD

**Issue by kdekooter** [criteo/JVips#95]

**Comment by dbouron** [comment]
Hello,

**Comment by dbouron** [comment]
Hello,
JVips is copying the jar embedded native libraries into the system temporary path with a unique filename: \<libname\>\<random_hash\>.so
If you call n times a program using JVips, you will get n x native libraires into your temp dir.
I have either to add a shutdown hook to delete temp files or copying (overwriting if present) libraries without random_hash.
I will try to work on it when I have free time

**Comment by kdekooter** [comment]
Can we somehow "keep JVips alive" between subsequent calls?

**Comment by dbouron** [comment]
I never tried but since we have to initialize libvips context, there is no guarantee that it is persistent.
Moreover, I could look if the native libraries are present or not in the temp dir but you can fall in the case that you upgrade JVips and the old dependencies are still present because you didn 't recycle your instance.
I have to think about the best balance...

**Comment by kdekooter** [comment]
You could put the files in the jvm-bound temp directory. The libraries can be put there once on JVM startup and will be wiped on shutdown. Subsequent jvips invocations in the application can use these libs.

**Comment by kdekooter** [comment]
I took a look at the source code and I think adding one line to `Vips.java` would already make a big difference:
```
temp.deleteOnExit()
```

**Comment by dbouron** [comment]
> You could put the files in the jvm-bound temp directory.

Indeed, deleteOnExit() seems to make the job. Why do you want to add a loadedLibraryList?

**Comment by kdekooter** [comment]
Maybe I do not understand your code fully... I added `loadedLibraryList` to prevent loading the same library twice. 

I noticed that on repeated invocations of `VipsImage` additional temp files were created.

**Comment by dbouron** [comment]
> I noticed that on repeated invocations of `VipsImage` additional temp files were created.

You mean when you call your program using JVips several times? Because if each time VipsImage is invocated, we extract libs, it is a bug

**Comment by kdekooter** [comment]
Yes I am using the library in a server that resizes images on-the-fly. It should be able to handle a lot of requests in the future. We stumbled upon the temp files issue while testing - we ran out of disk space.

Is the temp file needed after `System.load` is executed? If not we could delete the temp file immediately.

**Comment by dbouron** [comment]
No, we cannot remove the temp file because Java uses the default one in "ava.io.tmpdir". Usually, it is /tmp/

**Comment by kdekooter** [comment]
> if each time VipsImage is invocated, we extract libs, it is a bug

Is there a ticket for this bug? And can I maybe help out in fixing it?

**Comment by dbouron** [comment]
> if each time VipsImage is invocated

I test locally and I cannot reproduce. When I create 3 instances of VipsImage the library are loaded only once. It's probably because you call several time a program using JVips that you have the feeling that every time you instantiate a VipsImage, libs are loaded.

**Comment by dbouron** [comment]
This should fix your problem: https://github.com/criteo/JVips/pull/96
If you  still have libs extraction when you instantiate VipsImage, I will add a Set<String> loadedLibraries.
Please note that if you program is killed or crashes, deleteOnExit() doen't work.
