### ISSUE TITLE
Throw exception when loading corrupted image

### ISSUE THREAD

**Issue by TimoZikeli** [criteo/JVips#98]
Hi, 
it sometimes happens that a user-uploaded image binary data is corrupted. Java's `ImageIO` would throw an exception when parsing it, but JVips just processes it and some part of the image is simply gray. It would be nice if there was an **option to enable some kind of strict checking when loading a JPG image**.

Thanks!

**Comment by dbouron** [comment]
Hi,
I have to set the `fail` optional parameter to `true` in vips_jpegload() for example.
Do you please have a corrupted jpeg file for testing?

https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-jpegload

**Comment by dbouron** [comment]
@FylmTM did a [patch](https://github.com/criteo/JVips/pull/112) with option at image instantiation.
There is an example in the method test to enable failure on loading.
